# Используем базовый образ Node.js для сборки
FROM node:14-alpine AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект в контейнер
COPY . .

# Собираем приложение
RUN npm run build

# Используем базовый образ Nginx для сервировки статических файлов
FROM nginx:alpine

# Копируем файлы сборки во временную директорию Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Экспонируем порт 80
EXPOSE 80

# Запускаем сервер Nginx
CMD ["nginx", "-g", "daemon off;"]
