# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы requirements.txt
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . .

# Делаем start.sh исполняемым
RUN chmod +x start.sh

# Экспонируем порт 8000
EXPOSE 8000

# Запускаем приложение
CMD ["./start.sh"]
